import C1 from "/src/assets/pool/chemicals/pool-chemicals.jpg";
import C2 from "/src/assets/pool/chemicals/ecosalt-2.jpg";
import C3 from "/src/assets/pool/chemicals/poolchlor.jpg";
import C4 from "/src/assets/pool/chemicals/dayliff-sanitisers.jpg";



export const chemicals = [
    {
        image: C1,
        name: "Pool Chemicals",
        description: "A convenient pool chlorine doser that contains dissolvable Chlorine tablets and floats on the water surface providing constant water chlorination. Supplied in one size for pools up to 70,000 litres, larger pools are dosed with multiple units. Options of TCCA Chlorine 90 or Calcium Hypochlorite 65 tablets are available.",
        oldPrice: "Price",
        moreDescription:"More",

    },

    {
        image: C2,
        name: "Davey Eco Salt2 Water Chlorinator",
        description: "Davey Chlorinators are of exceptional design combining high flow, long life electrodes with a robust switch mode power supply to provide many years of trouble free operation. All models feature multilingual and user friendly LCD interface with data logging capability, adjustable reverse polarity self-cleaning cells, auto-turn off on low salt, low flow and overload indication.",
        oldPrice: "Price",
        moreDescription:"More",

    },

    {
        image: C3,
        name: "PoolChlor",
        description: "Salt Water Chlorination is now well established as an effective method of swimming pool sanitisation. Chlorinators work on the electrolysis process whereby salt in the water is separated into its basic elements which releases chlorine gas into the water.",
        oldPrice: "Price",
        moreDescription:"More",

    },

    {
        image: C4,
        name: "Pool Sanitisers",
        description: "Dayliff Solar Ioniser is a solar powered water purifier specially designed to control algae growth in a simple, non-toxic and cost effective way, the main applications being swimming pools, fish ponds, water gardens and water features. The unit features two copper electrodes, one a peripheral coil and the other a central sacrificial rod which erodes over time and with use. It floats on the water and works when exposed to sunlight, an electrical current being generated by the surface 3W, 6V PV solar panel.",
        oldPrice: "Price",
        moreDescription:"More",

    },

   
]